version: '3.8'

services:
  core-api:
    container_name: core-api
    image: core-api
    build: .
    ports:
      - "8090:8090"
    networks:
      - net
    restart: always

networks:
  net:
    external: true

